################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_CUCUMBER "cucumber")
    if (PC_CUCUMBER_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_CUCUMBER_CFLAGS} ${PC_CUCUMBER_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_CUCUMBER_INCLUDE_HINTS ${PC_CUCUMBER_INCLUDE_DIRS} ${PC_CUCUMBER_INCLUDE_DIRS}/*)
        set(PC_CUCUMBER_LIBRARY_HINTS ${PC_CUCUMBER_LIBRARY_DIRS} ${PC_CUCUMBER_LIBRARY_DIRS}/*)
    endif(PC_CUCUMBER_FOUND)
endif (NOT MSVC)

find_path (
    CUCUMBER_INCLUDE_DIRS
    NAMES cucumber_c.h
    HINTS ${PC_CUCUMBER_INCLUDE_HINTS}
)

find_library (
    CUCUMBER_LIBRARIES
    NAMES cucumber
    HINTS ${PC_CUCUMBER_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    CUCUMBER
    REQUIRED_VARS CUCUMBER_LIBRARIES CUCUMBER_INCLUDE_DIRS
)
mark_as_advanced(
    CUCUMBER_FOUND
    CUCUMBER_LIBRARIES CUCUMBER_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
