################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LEVELDB "leveldb")
    if (PC_LEVELDB_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LEVELDB_CFLAGS} ${PC_LEVELDB_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LEVELDB_INCLUDE_HINTS ${PC_LEVELDB_INCLUDE_DIRS} ${PC_LEVELDB_INCLUDE_DIRS}/*)
        set(PC_LEVELDB_LIBRARY_HINTS ${PC_LEVELDB_LIBRARY_DIRS} ${PC_LEVELDB_LIBRARY_DIRS}/*)
    endif(PC_LEVELDB_FOUND)
endif (NOT MSVC)

find_path (
    LEVELDB_INCLUDE_DIRS
    NAMES leveldb/c.h
    HINTS ${PC_LEVELDB_INCLUDE_HINTS}
)

find_library (
    LEVELDB_LIBRARIES
    NAMES leveldb
    HINTS ${PC_LEVELDB_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LEVELDB
    REQUIRED_VARS LEVELDB_LIBRARIES LEVELDB_INCLUDE_DIRS
)
mark_as_advanced(
    LEVELDB_FOUND
    LEVELDB_LIBRARIES LEVELDB_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
