Name(7)
=======


NAME
----
dafka - Overview of ZeroMQ messaging middleware


SYNOPSIS
--------

Project dafka aims to ... (short marketing pitch)

It delivers several programs with their respective man pages:
 dafka_console_producer.1 dafka_console_consumer.1 dafka_stored.1 dafka_towerd.1
and public classes in a shared library:
 dafka_consumer_msg.3 dafka_producer_msg.3 dafka_producer.3 dafka_consumer.3 dafka_proto.3 dafka_beacon.3 dafka_tower.3 dafka_store.3

Generally you can compile and link against it like this:
----
#include <dafka.h>

cc ['flags'] 'files' -ldafka ['libraries']
----


DESCRIPTION
-----------

This is a skeleton document created by zproject, which will not be
regenerated automatically (by Makefiles nor project.xml re-parsing).
You should add hand-written text here to detail whatever applies to
Linux standard manpage Section 7 (note that other OSes may follow
a different standard with similar concepts, and extend the recipes
to package this document into a different section number):

----
7 Overview, conventions, and miscellaneous :
    Overviews or descriptions of various topics, conventions
    and protocols, character set standards, the standard
    filesystem layout, and miscellaneous other things.
----

Classes
~~~~~~~

Something for developers to consider. Note there are separate man
pages generated for public classes during build with contents taken
from source code comments.

