/*  =========================================================================
    dafka - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of CZMQ, the high-level C binding for 0MQ:
    http://czmq.zeromq.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef DAFKA_LIBRARY_H_INCLUDED
#define DAFKA_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  DAFKA version macros for compile-time API detection
#define DAFKA_VERSION_MAJOR 0
#define DAFKA_VERSION_MINOR 1
#define DAFKA_VERSION_PATCH 0

#define DAFKA_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define DAFKA_VERSION \
    DAFKA_MAKE_VERSION(DAFKA_VERSION_MAJOR, DAFKA_VERSION_MINOR, DAFKA_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined DAFKA_STATIC
#       define DAFKA_EXPORT
#   elif defined DAFKA_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define DAFKA_EXPORT __declspec(dllexport)
#       else
#           define DAFKA_EXPORT
#       endif
#   elif defined DAFKA_EXPORTS
#       define DAFKA_EXPORT __declspec(dllexport)
#   else
#       define DAFKA_EXPORT __declspec(dllimport)
#   endif
#   define DAFKA_PRIVATE
#elif defined (__CYGWIN__)
#   define DAFKA_EXPORT
#   define DAFKA_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define DAFKA_PRIVATE __attribute__ ((visibility ("hidden")))
#       define DAFKA_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define DAFKA_PRIVATE
#       define DAFKA_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  DAFKA_BUILD_DRAFT_API
#define DAFKA_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef DAFKA_BUILD_DRAFT_API
typedef struct _dafka_publisher_t dafka_publisher_t;
#define DAFKA_PUBLISHER_T_DEFINED
typedef struct _dafka_proto_t dafka_proto_t;
#define DAFKA_PROTO_T_DEFINED
#endif // DAFKA_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef DAFKA_BUILD_DRAFT_API
#include "dafka_publisher.h"
#include "dafka_proto.h"
#endif // DAFKA_BUILD_DRAFT_API

#ifdef DAFKA_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
DAFKA_EXPORT void
    dafka_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // DAFKA_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
