/*  =========================================================================
    dafka_producer_msg - class description

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of CZMQ, the high-level C binding for 0MQ:
    http://czmq.zeromq.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef DAFKA_PRODUCER_MSG_H_INCLUDED
#define DAFKA_PRODUCER_MSG_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/dafka_producer_msg.api" to make changes.
//  @interface
//  This is a stable class, and may not change except for emergencies. It
//  is provided in stable builds.
//  Create a new dafka_producer_msg.
DAFKA_EXPORT dafka_producer_msg_t *
    dafka_producer_msg_new (void);

//  Destroy the dafka_producer_msg.
DAFKA_EXPORT void
    dafka_producer_msg_destroy (dafka_producer_msg_t **self_p);

//  Return the content of the record.
//  Content buffer is belong to the record and user should not try to free it.
DAFKA_EXPORT const byte *
    dafka_producer_msg_content (dafka_producer_msg_t *self);

//  Return the size of the content
DAFKA_EXPORT size_t
    dafka_producer_msg_content_size (dafka_producer_msg_t *self);

//  Return the content, user takes ownership of the buffer returned.
//  Caller owns return value and must destroy it when done.
DAFKA_EXPORT zframe_t *
    dafka_producer_msg_get_content (dafka_producer_msg_t *self);

//  Create a new content buffer at the specific size.
//  Return 0 on success and -1 if not enough memory.
DAFKA_EXPORT int
    dafka_producer_msg_init_content (dafka_producer_msg_t *self, size_t size);

//  Set the content with a frame. Takes ownership on the content.
DAFKA_EXPORT void
    dafka_producer_msg_set_content (dafka_producer_msg_t *self, zframe_t **content);

//  Set the content from string.
//  Return 0 on success and -1 if not enough memory.
DAFKA_EXPORT int
    dafka_producer_msg_set_content_str (dafka_producer_msg_t *self, const char *content);

//  Set the content from string.
//  Return 0 on success and -1 if not enough memory.
DAFKA_EXPORT int
    dafka_producer_msg_set_content_buffer (dafka_producer_msg_t *self, const byte *content, size_t content_size);

//  Send a record to producer.
//  Content will ownership will be moved to a background thread and will be set to NULL.
//  Return 0 on success and -1 on error.
DAFKA_EXPORT int
    dafka_producer_msg_send (dafka_producer_msg_t *self, zactor_t *producer);

//  Return frame data copied into freshly allocated string
//  Caller must free string when finished with it.
//  Caller owns return value and must destroy it when done.
DAFKA_EXPORT char *
    dafka_producer_msg_strdup (dafka_producer_msg_t *self);

//  Return TRUE if content is equal to string, excluding terminator
DAFKA_EXPORT bool
    dafka_producer_msg_streq (dafka_producer_msg_t *self, const char *string);

//  Self test of this class.
DAFKA_EXPORT void
    dafka_producer_msg_test (bool verbose);

//  @end

#ifdef __cplusplus
}
#endif

#endif
