The following ABNF grammar defines the dafka_proto:

    dafka_proto     = *( MSG | RELIABLE | ASK | ANSWER )

    ;  No description

    MSG             = signature %d'm' topic
    signature       = %xAA %xA0             ; two octets
    topic           = string                ;

    ;  No description

    RELIABLE        = signature %d'r' topic address sequence content
    topic           = string                ;
    address         = string                ;
    sequence        = number-8              ;
    content         = frame                 ;

    ;  No description

    ASK             = signature %d'a' topic subject begin_offset end_offset address
    topic           = string                ;
    subject         = string                ;
    begin_offset    = number-8              ;
    end_offset      = number-8              ;
    address         = string                ;

    ;  No description

    ANSWER          = signature %d'w' topic subject sender sequence content
    topic           = string                ;
    subject         = string                ;
    sender          = string                ;
    sequence        = number-8              ;
    content         = frame                 ;

    ; A frame is zero or more octets encoded as a ZeroMQ frame
    frame           = *OCTET

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-8        = 8OCTET
