The following ABNF grammar defines the dafka_proto:

    dafka_proto     = *( MSG | DIRECT-MSG | FETCH | ACK | HEAD | DIRECT-HEAD | GET-HEADS | CONSUMER-HELLO | STORE-HELLO )

    ;  Message from producer to consumers. The topic is either the subject or
    ;  recipient address.

    MSG             = signature %d'm' subject address sequence content
    signature       = %xAA %xA0             ; two octets
    subject         = string                ;
    address         = string                ;
    sequence        = number-8              ;
    content         = frame                 ;

    ;  Direct message from producer to consumer. The topic is the recipient
    ;  address.

    DIRECT-MSG      = signature %d'd' subject address sequence content
    subject         = string                ;
    address         = string                ;
    sequence        = number-8              ;
    content         = frame                 ;

    ;  Consumer publish the message when a message is missing. Topic is the
    ;  address of the producer (partition). Either the producer or a store
    ;  daemon can answer.

    FETCH           = signature %d'f' subject sequence count address
    subject         = string                ;
    sequence        = number-8              ;
    count           = number-4              ;
    address         = string                ;

    ;  Ack from a store daemon to a producer. Topic is the address of the
    ;  producer.

    ACK             = signature %d'k' subject sequence
    subject         = string                ;
    sequence        = number-8              ;

    ;  No description

    HEAD            = signature %d'h' subject address sequence
    subject         = string                ;
    address         = string                ;
    sequence        = number-8              ;

    ;  No description

    DIRECT-HEAD     = signature %d'e' subject address sequence
    subject         = string                ;
    address         = string                ;
    sequence        = number-8              ;

    ;  No description

    GET-HEADS       = signature %d'g' address
    address         = string                ;

    ;  No description

    CONSUMER-HELLO  = signature %d'w' address subjects
    address         = string                ;
    subjects        = strings               ;

    ;  No description

    STORE-HELLO     = signature %d'l' address
    address         = string                ;

    ; A list of string values
    strings         = strings-count *strings-value
    strings-count   = number-4
    strings-value   = longstr

    ; A frame is zero or more octets encoded as a ZeroMQ frame
    frame           = *OCTET

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
