/*  =========================================================================
    dafka_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file. This
    file is part of DAFKA, a decentralized distributed streaming
    platform: http://zeromq.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef DAFKA_CLASSES_H_INCLUDED
#define DAFKA_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/dafka.h"

//  Opaque class structures to allow forward references
#ifndef DAFKA_UNACKED_LIST_T_DEFINED
typedef struct _dafka_unacked_list_t dafka_unacked_list_t;
#define DAFKA_UNACKED_LIST_T_DEFINED
#endif
#ifndef DAFKA_FETCH_FILTER_T_DEFINED
typedef struct _dafka_fetch_filter_t dafka_fetch_filter_t;
#define DAFKA_FETCH_FILTER_T_DEFINED
#endif
#ifndef DAFKA_MSG_KEY_T_DEFINED
typedef struct _dafka_msg_key_t dafka_msg_key_t;
#define DAFKA_MSG_KEY_T_DEFINED
#endif
#ifndef DAFKA_HEAD_KEY_T_DEFINED
typedef struct _dafka_head_key_t dafka_head_key_t;
#define DAFKA_HEAD_KEY_T_DEFINED
#endif
#ifndef DAFKA_UTIL_T_DEFINED
typedef struct _dafka_util_t dafka_util_t;
#define DAFKA_UTIL_T_DEFINED
#endif
#ifndef DAFKA_STORE_READER_T_DEFINED
typedef struct _dafka_store_reader_t dafka_store_reader_t;
#define DAFKA_STORE_READER_T_DEFINED
#endif
#ifndef DAFKA_STORE_WRITER_T_DEFINED
typedef struct _dafka_store_writer_t dafka_store_writer_t;
#define DAFKA_STORE_WRITER_T_DEFINED
#endif
#ifndef DAFKA_TEST_PEER_T_DEFINED
typedef struct _dafka_test_peer_t dafka_test_peer_t;
#define DAFKA_TEST_PEER_T_DEFINED
#endif

//  Extra headers

//  Internal API

#include "dafka_unacked_list.h"
#include "dafka_fetch_filter.h"
#include "dafka_msg_key.h"
#include "dafka_head_key.h"
#include "dafka_util.h"
#include "dafka_store_reader.h"
#include "dafka_store_writer.h"
#include "dafka_test_peer.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef DAFKA_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
DAFKA_PRIVATE void
    dafka_unacked_list_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
DAFKA_PRIVATE void
    dafka_util_test (bool verbose);

//  Self test for private classes
DAFKA_PRIVATE void
    dafka_private_selftest (bool verbose, const char *subtest);

#endif // DAFKA_BUILD_DRAFT_API

#endif
